function fitRet = icm_init_fit_ret(cp)

fitRet = struct(...
    'fitobject',[],...
    'fitgof',struct(),...
    'movingHorizon',cp.MovingHorizonL,...
    'halfLife',cp.HalfLife,...
    'frameIdx_dummy',0,...
    'frameIdx',0,...
    'firstValidFoiIdx',0,...
    'fitStatus',0,...
    'fitoptions',fitoptions('fourier1'),...
    'I0',[],...
    'I1',[],...
    'freqW',0,...
    'freq',0,...
    'time',0);
